# Docker-compose file for deploy the service from the docker image in the github container registry
# Make sure to set the environment variables before running this file in a .env file
# Also make sure to create a folder called data/certs and put the certificates there
# The certificates must be named as follows:
#   - server.crt
#   - server.key

services:
  satec-notification-service:
    image: ghcr.io/uo276213/satec-notification-service-prod:latest
    container_name: satec-notification-service
    volumes:
      - static_volume:/app/staticfiles
      - database:/app/database
    expose:
      - 8000
    environment:
      - PUSH_API_APP_SERVER_KEY=$PUSH_API_APP_SERVER_KEY # Need to be set in .env file for Push API Conector
      - PUSH_API_PRIVATE_KEY=$PUSH_API_PRIVATE_KEY # Need to be set in .env file for Push API Conector
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS # Dominio del host
      - DJANGO_DATABASE=$DJANGO_DATABASE # Nombre de la base de datos
      - ID_SERVICE_REGISTER_SNS=$ID_SERVICE_REGISTER_SNS      # ID del servicio que envía mensajes de nuevos dueños de servicio
      - TOKEN_SERVICE_REGISTER_SNS=$TOKEN_SERVICE_REGISTER_SNS # Token de acceso al servicio que
                                                                # envía mensajes de nuevos dueños de servicio 
      - DJANGO_THIS_HOST=$DJANGO_THIS_HOST # HOST
      - DJANGO_DEBUG=$DJANGO_DEBUG # 1 para obtener los errores de la aplicación
    command:
      - /bin/bash
      - -c
      - |
        python manage.py collectstatic --noinput && \
        python manage.py migrate && \
        python manage.py manageconectors --add && \
        gunicorn --bind 0.0.0.0:8000 settings.asgi -w 4 -k uvicorn.workers.UvicornWorker
  nginx:
    image: nginx
    volumes: 
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certs:/etc/nginx/certs
    ports: 
      - 80:80
      - "443:443"
    depends_on: 
      - satec-notification-service

volumes:
  static_volume:
  database:
