services:
  satec-notification-service:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - DJANGO_SUPERUSER_USERNAME=$DJANGO_SUPERUSER_USERNAME
        - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
        - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
        - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
        - DJANGO_DATABASE=$DJANGO_DATABASE
    environment:
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
    command: gunicorn --bind 0.0.0.0:8000 settings.asgi -w 4 -k uvicorn.workers.UvicornWorker
    volumes:
      - static_volume:/app/staticfiles
      - database:/app/database
    expose:
      - 8000
  nginx:
    image: nginx
    volumes: 
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on: 
      - satec-notification-service

volumes:
  static_volume:
  database: