services:
  satec-notification-service:
    image: ghcr.io/uo276213/satec-notification-service-prod:latest
    container_name: satec-notification-service
    volumes:
      - ./app/:/app/
      - static_volume:/app/staticfiles
    expose: 
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 settings.asgi -w 4 -k uvicorn.workers.UvicornWorker
  nginx:
    image: nginx
    volumes: 
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on: 
      - satec-notification-service

volumes:
  static_volume:
