name:  Deploy on production

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy production code over SSH to azure
    runs-on: ubuntu-latest
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          rm nginx.conf
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://raw.githubusercontent.com/UO276213/satec-notification-service/main/nginx.conf
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://raw.githubusercontent.com/UO276213/satec-notification-service/main/docker-compose.deploy.yml -O docker-compose.yml
          docker compose stop
          docker compose rm -f
          docker compose pull   
          docker compose up -d