name:  CI satec-notification-service 

on:
  push:
    branches: 
    - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./app/requirements.txt
    - name: Run Tests
      run: |
        cd app
        python manage.py test --parallel
  docker-push-for-develop:
    name: Push code Docker Image to Github Packages
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: ./app
        name: UO276213/satec-notification-service
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: app/Dockerfile
  docker-push-gunicorn-nginx:
    name: Push Docker Image to Github Packages with Gunicorn and Nginx for production
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: ./app
        name: UO276213/satec-notification-service-prod
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: app/Dockerfile.prod
        
  deploy:
    name: Deploy production code over SSH to azure
    runs-on: ubuntu-latest
    needs: [build-and-test, docker-push-gunicorn-nginx]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://raw.githubusercontent.com/UO276213/satec-notification-service/main/nginx.conf
          wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://raw.githubusercontent.com/UO276213/satec-notification-service/main/docker-compose.deploy.yml -O docker-compose.yml
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull   
          sudo docker-compose up -d